# Generated by Django 5.1.4 on 2024-12-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.TextField(max_length=100),
        ),
    ]
